# Generated by Django 4.2.7 on 2023-12-09 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayhen', models.DateField()),
                ('vaoLuc', models.TimeField()),
                ('thoiLuong', models.DurationField()),
                ('comeBy', models.CharField(choices=[('WebSite', 'Online'), ('Phone Call', 'Call'), ('Cancel', 'Cancel'), ('Arrived', 'Arrived')], default='WebSite', max_length=12)),
                ('khach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.khach')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.service')),
                ('tech', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.technician')),
            ],
        ),
    ]
