# Generated by Django 4.2.1 on 2023-10-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_delete_dathen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayhen', models.DateField()),
                ('vaoLuc', models.TimeField()),
                ('comeBy', models.CharField(choices=[('WebSite', 'Online'), ('Phone Call', 'Call'), ('Cancel', 'Cancel')], default='WebSite', max_length=12)),
                ('khach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.khach')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.service')),
                ('tech', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.technician')),
            ],
        ),
    ]
