# Generated by Django 4.2.1 on 2023-10-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_delete_dathen'),
        ('datHen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathen',
            name='khach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.khach'),
        ),
    ]
