# Generated by Django 4.2.7 on 2023-12-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_service_time_serv_alter_khach_desc_and_more'),
        ('datHen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathen',
            name='khach',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.khach'),
        ),
    ]
