# Generated by Django 4.2.7 on 2023-12-13 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Khach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=35, null=True)),
                ('diem', models.PositiveIntegerField(default=0)),
                ('ngaydau', models.DateTimeField(auto_now_add=True)),
                ('day_comes', models.DateField()),
                ('time_at', models.TimeField()),
                ('desc', models.TextField(blank=True, max_length=250, null=True)),
                ('comeBy', models.CharField(choices=[('WebSite', 'Online'), ('Phone Call', 'Call'), ('Cancel', 'Cancel'), ('Arrived', 'Arrived')], default='WebSite', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('isWork', models.BooleanField(default=False)),
                ('clients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='ledger.khach')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dichVu', models.CharField(max_length=30)),
                ('gia', models.FloatField()),
                ('thoiLuong', models.DurationField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='khach',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='dichvu', to='ledger.service'),
        ),
        migrations.AddField(
            model_name='khach',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.technician'),
        ),
        migrations.AlterUniqueTogether(
            name='khach',
            unique_together={('full_name', 'phone')},
        ),
    ]
