# Generated by Django 4.2.1 on 2023-06-04 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Khach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=35, null=True)),
                ('diem', models.PositiveIntegerField(default=0)),
                ('ngay', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(blank=True, max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=12)),
                ('clients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='ledger.khach')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dichVu', models.CharField(max_length=30)),
                ('gia', models.FloatField()),
                ('time_serv', models.DurationField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='khach',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.service'),
        ),
        migrations.AddField(
            model_name='khach',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.technician'),
        ),
        migrations.CreateModel(
            name='DatHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayhen', models.DateField()),
                ('vaoLuc', models.TimeField()),
                ('khach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.khach')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.service')),
            ],
        ),
    ]
