# Generated by Django 4.2.7 on 2023-12-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khach',
            old_name='ngayhen',
            new_name='day_comes',
        ),
        migrations.RenameField(
            model_name='khach',
            old_name='vaoluc',
            new_name='time_at',
        ),
    ]
