# Generated by Django 4.0.7 on 2023-04-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='khach',
        ),
        migrations.AddField(
            model_name='khach',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.service'),
        ),
    ]
