# Generated by Django 4.2.1 on 2023-06-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatHen',
        ),
    ]
