# Generated by Django 4.0.7 on 2023-03-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khach',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='khach',
            name='email',
            field=models.EmailField(max_length=35, null=True),
        ),
    ]
