# Generated by Django 4.2.7 on 2023-12-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_delete_dathen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='time_serv',
        ),
        migrations.AlterField(
            model_name='khach',
            name='desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='khach',
            name='email',
            field=models.EmailField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='khach',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.service'),
        ),
        migrations.AlterField(
            model_name='khach',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.technician'),
        ),
    ]
