# Generated by Django 4.0.7 on 2023-03-19 02:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_name_khach_full_name_alter_khach_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='khach',
            name='desc',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='khach',
            name='diem',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khach',
            name='ngay',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dichVu', models.CharField(max_length=30)),
                ('gia', models.FloatField()),
                ('khach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.khach')),
            ],
        ),
    ]
