# Generated by Django 4.2.7 on 2023-12-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_service_khach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khach',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='dichvu', to='ledger.service'),
        ),
    ]
