# Generated by Django 4.2.7 on 2023-12-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_service_time_serv_alter_khach_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khach',
            name='owner',
        ),
    ]
